apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: next-todo-argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AshishBadgujar/next-todo-configs
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
