apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-todo
spec:
  selector:
    matchLabels:
      app: next-todo
  template:
    metadata:
      labels:
        app: next-todo
    spec:
      containers:
        - name: next-todo
          image: dkrashi/next-todo:1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: next-todo-service
spec:
  selector:
    app: next-todo
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
